Allow for specifying protocol and API base path
s12v/newrelic-elasticsearch pull request #46
Opened 2016-12-07 17:29 UTC by bellpeterm

I work in an environment where the ElasticSearch API is using HTTPS and its base path is /elasticsearch so both of these improvements are needed.  I thought it might be useful for others too.

2016-12-07 20:14 UTC, s12v requested changes
Thanks for the PR. Looks good, 2 minor comments and 👍

2016-12-07 20:14 UTC, s12v commented on src/main/java/me/snov/newrelic/elasticsearch/parsers/NodesStatsParser.java
> +        super(NodesStats.class, new URL(protocol, host, port, basePath + URL_CLUSTER_STATS), username, password);
please cover a case, when the path ends with `/`?

2016-12-07 20:14 UTC, s12v commented on src/main/java/me/snov/newrelic/elasticsearch/ElasticsearchAgentFactory.java
> +        if (protocol == null) {
could you please add the new options to the example configuration?

2016-12-07 22:21 UTC, bellpeterm commented
Great feedback.  Updated PR.

Added case to drop '/' if it is last character in basePath.
Added documentation for basePath option in line with other optional parameter.

2016-12-11 10:51 UTC, s12v commented
@bellpeterm, thank you. Could you please also add "protocol" to the example config?

2016-12-12 18:38 UTC, bellpeterm commented
@s12v my mistake.  Updated the config again in the pull request.  Cheers!

2016-12-12 20:25 UTC, s12v approved these changes

2016-12-12 20:26 UTC, merged

2016-12-12 20:26 UTC, s12v commented
thank you @bellpeterm